Add RewardV1 contract
radicle-dev/radicle-orgs pull request #3
Opened 2021-10-18 15:21 UTC by sebastinez

This PR works on the ERC721 Code Contribution Reward Contract.

It provides the `claimRewardEOA` functionality which provided with information about the org, contributor, commit and project and the signature created by a Org, allows the contributor to claim a NFT token proving his contribution. 

Related: https://github.com/radicle-dev/radicle-client-tools/issues/8

2021-10-27 12:05 UTC, sebastinez commented
@cloudhead @ryanmtate Please feel free to provide feedback and reviews.

2021-10-27 13:36 UTC, Ryanmtate requested changes
Overall looks good; biggest concern is the `burn` method which appears to allow anyone to burn another's token.

2021-10-27 13:36 UTC, Ryanmtate commented on src/RewardV1.sol
> +        require(!isMinted(_puzzle.commit), "Reward: Failed to verify, that commit has not been minted");
Since we're checking the puzzle commit has not (!) been minted, shouldn't the error message read:

> Reward: Failed to verify, that commit has ~~not~~ already been minted

2021-10-27 13:36 UTC, Ryanmtate commented on src/RewardV1.sol
> +        _setApprovalForAll(msg.sender, operator, approved);
It seems `_setApprovalForAll` is only used once here in the contract. Is there a reason to have both the public and internal methods?

2021-10-27 13:36 UTC, Ryanmtate commented on src/RewardV1.sol
> +    function safeTransferFrom( address from, address to, uint256 tokenId) public {
Is `safeTransferFrom` materially different from `transferFrom`, it appears they both do the same thing?

2021-10-27 13:36 UTC, Ryanmtate commented on src/RewardV1.sol
> +    function _safeTransfer( address from, address to, uint256 tokenId) internal {
Same here-- is `_safeTransfer` materially different from `_transfer` ?

2021-10-27 13:36 UTC, Ryanmtate commented on src/RewardV1.sol
> +    function burn(uint256 tokenId) public virtual {
What prevents someone from burning a token belonging to another address?

Shouldn't this method check first if the `msg.sender` is approved to burn?

2021-10-27 13:36 UTC, Ryanmtate commented on src/RewardV1.t.sol
> +contract RewardV1Test is DSTest {
May want to add a test to ensure a non-approved sender cannot burn another's token.

2021-10-27 13:41 UTC, sebastinez commented on src/RewardV1.sol
> +    function burn(uint256 tokenId) public virtual {
Uff you're right. Thanks for the catch!!

Yeah we shoud check if is approved or if it's the owner before burning it.

2021-10-27 13:49 UTC, sebastinez commented on src/RewardV1.sol
> +    function safeTransferFrom( address from, address to, uint256 tokenId) public {
The public `safeTransferFrom` is the entry point with the `require`s and the internal `safeTransferFrom` is the bare method.
I guess we can avoid separating it to keep it simple, what do you think @cloudhead?

2021-10-27 13:58 UTC, sebastinez commented on src/RewardV1.sol
> +        _setApprovalForAll(msg.sender, operator, approved);
In this case, the public method complies with the EIP721 standard while the internal one checks that the operator is not equal to the owner, to avoid owners approving themselves..

2021-10-27 19:22 UTC, sebastinez commented on src/RewardV1.sol
> +    function burn(uint256 tokenId) public virtual {
@Ryanmtate @cloudhead Okay since I'm touching the burn method, I thought what should we do with the `commitMinted` and `commitContributors` mapping?

Regarding the `commitMinted` mapping I think that if we delete it while burning the token, one could claim the reward again and again and again. So we should keep it, even if the NFT gets burned.
And I would say the same for `commitContributors` and keep it as a historical state. To see for which commit a claim was made, even if the nft was burned afterwards.

What do you think?

2021-10-27 19:44 UTC, Ryanmtate commented on src/RewardV1.sol
> +    function burn(uint256 tokenId) public virtual {
I think it makes sense to keep the mappings to prevent re-minting. I think the burn method should also assert whether the owner of the `tokenId` is not `address(0)`

2021-10-27 19:45 UTC, Ryanmtate commented on src/RewardV1.sol
> +    function burn(uint256 tokenId) public virtual {
er, just saw that `ownerOf` has this assertion already.

2021-10-28 07:45 UTC, sebastinez commented
Reading again through the EIP721 spec I stumbled upon some discrepancies regarding how I implemented tokenURIs.
Will do update of the entire contract.

2021-11-04 10:05 UTC, sebastinez commented
@cloudhead @Ryanmtate
Ok, rewrite done, I think it's much more robust now.
Have 2 issues still left, which I would like to see with one of you guys.
- [ ] The puzzle is being signed by a predefined ORG_OWNER with a also pre-defined SECRET_KEY eventually there is a better way?
- [ ] The `createSignature` function in the test contract is not really reliable, it works depending on the input hash one provides. Any suggestions are welcome.

2021-11-09 12:32 UTC, cloudhead commented
>  The puzzle is being signed by a predefined ORG_OWNER with a also pre-defined SECRET_KEY eventually there is a better way?

You mean in the test? You could do a property test by generating secret keys based on `uint256`. See https://github.com/dapphub/dapptools/tree/master/src/dapp#property-based-testing

That way you test a bunch of combinations, not just one.

2021-11-12 13:37 UTC, sebastinez commented
> * [x]  The puzzle is being signed by a predefined `ORG_OWNER` with a also pre-defined `SECRET_KEY` eventually there is a better way?
> * [x]  The `createSignature` function in the test contract is not really reliable, it works depending on the input hash one provides. Any suggestions are welcome.

Ok fixed this by allowing malleable signatures and reduced the default values by using property based testing :+1:

2021-11-18 10:52 UTC, cloudhead approved these changes

2021-11-18 10:52 UTC, cloudhead commented
LGTM!

There are a few things we can fix later, eg. the name of the token etc.

2021-11-18 10:54 UTC, merged